<?php
return array(
    // main.php home/admin.php
    'APPLY NOW' => '立即申請',
    'months' => '個月',
    'MENU' => '目錄',
    'Global Club' => '環球會',
    'Personal Profile' => '個人檔案',
    'Login' => '登入',
    'LOGIN' => '登入',
    'Logout' => '登出',
    'Register' => '登記',
    'REGISTER' => '登記',
    'Home' => '首頁',
    'About us' => '關於我們',
    'About GICL' => '關於GICL',
    'Contact us' => '聯繫我們',
    'CONTACT US' => '聯繫我們',
    'FAQ' => '常見問題',
    'Language' => '語言',
    'Others' => '其他',
    'PERSONAL LOAN' => '私人貸款',
    'EASY FOR EVERYONE' => '',
    'I want to borrow' => '理想備用額',
    'over' => '貸款期',
    'Monthly repayment' => '每月還款額',
    'Calculated at {rate}% interest monthly' => '以月息{rate}%貸計算',
    'PLAY MOVIE' => '點擊看片',
    'FEATURE OF AirPin' => 'AirPin 特色',
    'A QUICK &amp; TRANSPARENT PROCESS' => '流程快速透明',
    'Fast approvals' => '特快批核',
    'Full online application, no more sifting through paperwork.' => '特快批核',
    'APPLICATION' => '申請',
    'A QUICK &amp;<br/>TRANSPARENT PROCESS' => '流程快速透明',
    'NO EXTRA CHARGE' => '＄0手續費',
    'Anytime advanced repayment without any extra charges.' => '隨時清還，<br>無提前清還手續費',
    'LIGHT RATES' => '低利率',
    'We look beyond your credit score to charge some of the lowest rates around.' => '按照你的個人信貸評分提供最合理的利率。',
    'CALCULATE YOU LOAN REPAYMENT' => '計算還款計劃',
    'Calculate' => '計算',
    'CALCULATE YOU LOAN REPAYMENT' => '計算還款計劃',
    'LOAN<br/>REPAYMENT' => '還款計劃',
    'LOAN REPAYMENT' => '還款計劃',
    'Use our loan calculator to plan your loan and repayment.' => '使用貸款計算器，規劃你的貸款及還款計劃',
    'Simple, Convenient, takes less than 2 minutes.' => '方便簡單，只需兩分鐘網上填寫',
    'Instant accessment results.' => '即時得知審批結果',
    'Service Videos' => '最新廣告',
    '2015 GIGL x Smart Mortage' => '2015 GICL 環球信貸 x 醒目樓按篇',
    'Benefits that<br/>meets your needs' => '多項好處滿足您的需求',
    'Credit Building' => '建設信用評分',
    'On-time payments are reported to major credit bureaus to help you build or improve your credit score.' => '準時還款幫您建立或改善你在信用局的信用評分',
    'Apply at Ease' => '容易申請',
    'What you see is what you get, we don\'t charge you any hidden fees to borrow money.' => '我們不會收取任何隱藏費用',
    'Real Customer service' => '真正的客戶服務',
    'Have a question? We\'re here 7 days a week to give you answers.' => '若有任何問題嗎？我們隨時為你提供答案',

    // login.php
    'Forget Password' => '忘記密碼',
    'FORGET PASSWORD' => '忘記密碼',
    'Can\'t log in? Forget your password?' => '無法登錄？ 忘記密碼了嗎？',
    'Enter your email address below and we\'ll send you password reset instructions' => '請輸入您的電子郵件地址，我們將發送您的密碼重置說明',
    'Enter your email address' => '請輸入電郵地址',
    'SEND' => '傳送',
    'BACK' => '返回',
    'WELCOME' => '歡迎',
	'Welcome' => '歡迎',
    'If you wish to apply for a loan, please register an account.' => '如欲申請貸款，請先登記帳號。',
    'Registered Email' => '註冊電子郵件',
    'Password' => '密碼',
    'CANCEL' => '取消',
    'Login Name' => '用戶名',
    'Your password must be at least 6 characters in length' => '您的密碼長度必須至少6個字符，其中包括符號。',
    'Re-type Password' => '重新輸入密碼',
    'I agree to receive news and updates from GIGL. By clicking "REGISTER" you confirm that you have read and accepted our Importance Notice and Personal Data Privacy Notice.'
    => '我同意接收環球信貸的新聞及更新。點擊“註冊”視為您確認已經閱讀並接受我們的重要性及注意事項個人資料隱私聲明。',
    'I do not want to receive news and updates from GICL.' => '我不接收環球信貸的新聞及更新',
    'THANK YOU FOR YOUR REGISTRATION' => '恭喜您已成功註冊',
    'Thank you for registering with Intersil. Your account has been created, and a verification email has been sent to your registered email address. Please click on the verification link included in the email to activate your account.'
    => '感謝您註冊。您的帳戶已經建立，驗證郵件將發送到您註冊的電子郵件地址，請登入並點擊信件內的連結來啟動您的帳戶驗證。',
    'Important! Your account will not be activated until you verify your email address.'
    => '重要啟示！您的帳戶未能啟動，請於您的電子郵件中啟動確認信。',
    'BACK TO MAIN' => '返回主頁',

    // profile.php
    'WELCOME, {username}' => '歡迎, {username}',
    'Member Since {date}' => '會員開始於 {date}',
    'Profile information' => '個人檔案',
    'Approval Status' => '審核狀態',
    'Payment Schedule' => '還款時間表',
    'Mobile' => '聯繫電話',
    'Email' => '電郵',
    'Proof Address' => '住址證明',
    'About Profile' => '關於個人資料',
    'UPDATE' => '更新',

    'Application No' => '申請號碼',
    'Submit Document' => '提交文件',
    'Download Contract' => '下載合約',
    'Sign Contract' => '下載合約',
    'Download' => '下載',

    'Principal' => '本金',
    'Interest' => '利息',
    'Payment' => '付款',
    'Balance' => '餘額',
    'Status' => '狀態',

    'Application' => '申請號碼',
    'Due Date' => '截止日期',
    'Loan Effective date' => '貸款生效日期',

    // upload.php
    'SUBMIT DOCUMENT' => '提交文件',
    'please submit the following documents is order to support you application.'
    => '請以提交下列申請文件。',
    'If there is any enquiry,please contact:{tel}.' => '若有任何疑問，請致電：{tel}。',
    'Photocopy of HKID' => '身份證影印本',
    'Proof of address from the past 3 months' => '住址證明(三個月內)',
    'Proof of income of the past 3 months. ( e.g. payroll slip / MPF contribution statement / autopay record)' => '近三個月的收入證明 ( 例如:薪金單/ 強積金供款紀錄 / 自動轉帳記錄)',
    'Bank statement of the past 3 months (with your name and account number)'
    => '近三個月的銀行對賬單（包含您的姓名和賬號）',
    'Drag your files here <span>or click to browse</span>' => '請拖曳檔案致此<span>或點繫開啟</span>',

    // signContract.php
    'SIGN CONTRACT' => '簽訂合約',
    'Loan Agreement' => '貸款協議',
    'Memorandum' => '備忘錄',
    'Confirmation' => '確認',
    'Confirmation of Important Loan Terms' => '重要的貸款條件確認',
    'START NOW' => '立即開始',
    'Loan Amortization Schedule' => '貸款分期償付時間表',
    'I have read and aggress to the agreement 1' => '我已閱讀並同意貸款協議 1',
    'Please input the password you received at your mobile phone to the sign contract.'
    => '請輸入您手機上所收到的密碼來簽訂合約。',
    'RESEND SMS' => '重發短信',
    'I have read and agree to the memorandum' => '我已閱讀並同意備忘錄',
    'SEND VERIFICATION CODES' => '發送驗證碼',
    'CONGRATULATIONS' => '恭喜你',
    'YOUR CONTRACT IS SIGNED' => '您已簽訂合約',
    'We will send you an SMS once the confirmation is done and the fund is ready to be transferred to your account, please pay attention to your SMS.'
    => '當審核通過我們將發送短信至你的電話。該貸款將會直接轉到您的帳戶，請留意你的電話短訊。',
    'Thank you.' => '謝謝。',

    // apply.php
    'PERSONAL LOANS' => '私人貸款',
    'Overview' => '概觀',
    'GICL offer a maximum loan of up to HK$300,000. For professionals such as doctors, solicitors, engineers, teachers, bank staff, etc., the maximum loan amount is up to HK$500,000.'
    => '環球信貸貸款額最⾼可達三十萬，各類專業人仕,如醫生、律師、工程師、教師及銀⾏行職員等等,專享最高達五十萬貸款額。',
    'Read More' => '了解更多',
    'Can we help?' => '更多幫助',
    'Pick the' => ' ',
    'Please select' => '請選擇',
    'LOAN TYPE' => '貸款類型',
    'Loan Type' => '貸款類型',
    'Tell Us' => ' ',
    'ABOUT YOURSELF' => '關於自己',
    'Tell us about' => ' ',
    'YOUR JOB' => '你的工作',
    'SUBMIT' => '提交',
    'Loan Purpose' => '貸款用途',
    'Loan Amount' => '貸款金額',
    'Tenor' => '分期',
    'Property Value' => '資產價值',
    'Mortgage Outstanding' => '未償還按揭',
    'I agree to receive news and updates from GICL. By clicking "Apply" you confirm that you have read and accepted our Important Notice and Personal Data Privacy Notice.'
    => '我同意從環球信貸接收新聞及資訊更新。點擊申請同時表示您已經閱讀並接受我們的重要事項及個人數據的私隱聲明。',
    'NEXT' => '下一頁',
    'PREVIOUS' => '上一頁',

    'Personal Information' => '個人資料',
    'Preferred Language' => '語言',
    'First Name' => '名字',
    'Surname' => '姓氏',
    'Gender' => '性別',
    'FEMALE' => '女',
    'MALE' => '男',
    'HK ID Number*' => '香港身份證號碼*',
    'Date Of Birth' => '出生日期',
    'yyyy/mm/dd' => '(年/月/日)',
    'Education Level' => '教育程度',
    'Education' => '教育程度',
    'Home Phone' => '住宅電話',
    'NO of Dependents' => '家庭人數',
    'Number of Departments' => '家庭人數',
    'Residential Address' => '住址',
    'Room/Floor/Building' => '室號/樓層/大廈/屋苑',
    'Street/Estate' => '街道/村',
    'Ownership' => '產權',
    'Home Address' => '住址',
    'Monthly Mortgage / Rental amount' => '每月按揭供款/租金金額',
    '*Global International Credit Limited only accept any Hong Kong permanent resident aged 18 or above.' => '* 環球信貸私人貸款只接受香港永久性居民申請。',

    'Job Information' => '工作資料',
    'Company Name' => '公司名稱',
    'Self Employed?' => '自僱人士？',
    'Years of Services' => '服務年資',
    'Company Phone' => '公司電話',
    'Industry' => '行業',
    'Position' => '職位',
    'Monthly Income' => '月收入',
    'Method of getting paid' => '薪金領取方式',
    'Company Address' => '公司地址',

    'Loan Information' => '貸款資料',
    'EDIT' => '編輯',
    'SAVE' => '保存',

    'Your Application is approved' => '你的申請已獲批准',
    'HK' => '港幣',
    'with' => '和',
    'tenor' => '個月還款期',
    'interest monthly' => '月息',
    'monthly payment of HK' => '每月HK',
    'Please upload your documents, an we will contact you once we have verified your application documents.' => '請上載您的文件，我們將會在確認您的申請文件後與你聯絡。',
    'Thank you for your application. We have assessed your application and regret to inform you that it has not gained an immediate approval. For more information, please call 3575 1099 during office hours.'  => '閣下的信貸記錄未能通過即時批核，多謝申請。 如欲了解更多，請於辦公時間致電3575 1099與我們聯絡。',
    'Your application has been submitted.' => '申請已遞交',
    'However, the credit report provided has not satisfied the criteria for an instant approval. Please provide the supplementary documents via e-mail or our mobile application at your earliest convenience so we can access your application. You can check the status of your application by logging into our system.' => '由於閣下的信貸紀錄不足以通過即時批核, 請立即上載文件，或以電郵或手機程式將您的文件遞交以盡快通過核實。閣下亦可以自行登入系統觀看批核狀態。',
    'Remarks:' => '備註:',
    'Based on the information provided at the initial stage, the lender is qualified for loan subject to verification of credit reports. The final approval may vary according to assessment of last submission and the most recent credit records.' => '顯示之貸款初步批核結果僅供參考。有關批核乃根據客戶於申請時確認之資料而得出之批核結果，最終或按客戶最後提交之申請資料及最新信貸紀錄而有所不同。',
    'SUBMIT LATER' => '稍後提交',

    // apply.php tips
    'Please fill in purpose value' => '請輸入貨款用途',
    'Please fill in amount value' => '請輸入貨款金額',
    'Please enter a value between 10000 and 300000' => '請輸入10000到300000之間的金額',
    'Please fill in intenor value' => '請輸入分期',
    'Please fill in sign' => '請同意',
    'Please fill in language value' => '請輸入語言',
    'Please fill in firstname' => '請輸入名字',
    'Please fill in surname' => '請輸入姓氏',
    'Please fill in gender' => '請輸入性別',
    'Please fill in ID Number' => '請輸入身份證號碼',
    'Please fill in date' => '請輸入出生日期',
    'Please fill in Mobile' => '請輸入聯繫電話',
    'Please enter valid Mobile' => '請輸入有效的聯繫電話',
    'Please fill in education level' => '請輸入教育程度',
    'Please fill in home tel' => '請輸入住宅電話',
    'Please enter valid Tel' => '請輸入有效的住宅電話',
    'Please fill in NO of Dependents' => '請輸入家庭人數',
    'Please fill in address' => '請輸入住址',
    'Please fill in address area' => '請輸入街道',
    'Please fill in ownership' => '請輸入產權',
    'Please fill in mortgage' => '請輸入每月住宅供款/租金金額',
    'Please fill in company name' => '請輸入公司名稱',
    'Please fill in answer' => '請輸入回答',
    'Please fill in years of server' => '請輸入服務年資',
    'Please enter valid years of server' => '請輸入有效的年資',
    'Please fill in company phone' => '請輸入公司電話',
    'Please enter valid company phone' => '請輸入有效的公司電話',
    'Please fill in Industry' => '請輸入行業',
    'Please fill in position' => '請輸入職位',
    'Please fill in monthly income' => '請輸入月收入',
    'Please fill in salary method' => '請輸入薪金領取方式',
    'Please fill in comepany address' => '請輸入住址',
    'Please fill in comepany address area' => '請輸入街道',

    // service.php
    'Maxium Loan for Specific Parties' => '特定對象的最高貸款額',
    'Doctors' => '醫生',
    'Solicitors' => '律師',
    'Teachers' => '教師',
    'Bank Staff' => '銀行工作人員',

    // contact-us.php
    'Welcome to contact us when you have any question.' => '如你有任何問題，歡迎與我們聯繫',
    'Like our Facebook page' => '讚好我們的Facebook專頁',

    // faq.php
    'FAQS' => '常見問題',

    'Other link' => '其他鏈接',
    'Products' => '產品',
    'Membership' => '會員',
    'Find us on' => '追踨環球',
    'Back to Top' => '回到頂部',
    'Copyright 2015 &copy; Global International Credit Limited . All Rights Reserved' => '環球信貸有限公司及環球物業按揭有限公司為環球信貸集團有限公司之附屬公司
香港中環德輔道中19號環球大廈23樓2301室',
    'Money Lenders Licence No. 0061 / 2015' => '放債人公司牌照號碼: 0062 / 2016 & 1605 / 2015',
		
	//loan status
	'Applying'=>'申請中',
	'Waiting for submission of document'=>'等待上傳資料',
	'Pending approval'=>'等待審核',
	'Rejected'=>'拒絕',
	'Ready to sign contract'=>'準備簽合約',
	'Waiting for confirmation'=>'合約等待確認',
	'Repaying'=>'還款中',
	'Complete'=>'全數清還',

);
